version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rbs-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --requirepass "h0Kszvjzv7SwMhJM"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'h0Kszvjzv7SwMhJM', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local
